# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "79a596ef41cdc7a7375d2c34c85215ea"
name = "custom-section-app"
handle = "custom-section-app"
application_url = "https://updates-commons-velocity-unable.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-5d7ff49b.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://updates-commons-velocity-unable.trycloudflare.com/auth/callback",
  "https://updates-commons-velocity-unable.trycloudflare.com/auth/shopify/callback",
  "https://updates-commons-velocity-unable.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
